/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  CustomFieldListEntry as PrismaCustomFieldListEntry,
} from "@prisma/client";

export class CustomFieldListEntryServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.CustomFieldListEntryCountArgs, "select">
  ): Promise<number> {
    return this.prisma.customFieldListEntry.count(args);
  }

  async customFieldListEntries(
    args: Prisma.CustomFieldListEntryFindManyArgs
  ): Promise<PrismaCustomFieldListEntry[]> {
    return this.prisma.customFieldListEntry.findMany(args);
  }
  async customFieldListEntry(
    args: Prisma.CustomFieldListEntryFindUniqueArgs
  ): Promise<PrismaCustomFieldListEntry | null> {
    return this.prisma.customFieldListEntry.findUnique(args);
  }
  async createCustomFieldListEntry(
    args: Prisma.CustomFieldListEntryCreateArgs
  ): Promise<PrismaCustomFieldListEntry> {
    return this.prisma.customFieldListEntry.create(args);
  }
  async updateCustomFieldListEntry(
    args: Prisma.CustomFieldListEntryUpdateArgs
  ): Promise<PrismaCustomFieldListEntry> {
    return this.prisma.customFieldListEntry.update(args);
  }
  async deleteCustomFieldListEntry(
    args: Prisma.CustomFieldListEntryDeleteArgs
  ): Promise<PrismaCustomFieldListEntry> {
    return this.prisma.customFieldListEntry.delete(args);
  }
}
