/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsInt,
  Min,
  Max,
  IsNumber,
} from "class-validator";
import { AppointmentUpdateManyWithoutPropertiesInput } from "./AppointmentUpdateManyWithoutPropertiesInput";
import { Type } from "class-transformer";
import { ImageCustomFieldUpdateManyWithoutPropertiesInput } from "./ImageCustomFieldUpdateManyWithoutPropertiesInput";
import { ListCustomFieldUpdateManyWithoutPropertiesInput } from "./ListCustomFieldUpdateManyWithoutPropertiesInput";
import { NormalCustomFieldUpdateManyWithoutPropertiesInput } from "./NormalCustomFieldUpdateManyWithoutPropertiesInput";
import { PropertyTranslationUpdateManyWithoutPropertiesInput } from "./PropertyTranslationUpdateManyWithoutPropertiesInput";

@InputType()
class PropertyUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: () => AppointmentUpdateManyWithoutPropertiesInput,
  })
  @ValidateNested()
  @Type(() => AppointmentUpdateManyWithoutPropertiesInput)
  @IsOptional()
  @Field(() => AppointmentUpdateManyWithoutPropertiesInput, {
    nullable: true,
  })
  appointments?: AppointmentUpdateManyWithoutPropertiesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => ImageCustomFieldUpdateManyWithoutPropertiesInput,
  })
  @ValidateNested()
  @Type(() => ImageCustomFieldUpdateManyWithoutPropertiesInput)
  @IsOptional()
  @Field(() => ImageCustomFieldUpdateManyWithoutPropertiesInput, {
    nullable: true,
  })
  imageCustomFields?: ImageCustomFieldUpdateManyWithoutPropertiesInput;

  @ApiProperty({
    required: false,
    type: () => ListCustomFieldUpdateManyWithoutPropertiesInput,
  })
  @ValidateNested()
  @Type(() => ListCustomFieldUpdateManyWithoutPropertiesInput)
  @IsOptional()
  @Field(() => ListCustomFieldUpdateManyWithoutPropertiesInput, {
    nullable: true,
  })
  listCustomFields?: ListCustomFieldUpdateManyWithoutPropertiesInput;

  @ApiProperty({
    required: false,
    type: () => NormalCustomFieldUpdateManyWithoutPropertiesInput,
  })
  @ValidateNested()
  @Type(() => NormalCustomFieldUpdateManyWithoutPropertiesInput)
  @IsOptional()
  @Field(() => NormalCustomFieldUpdateManyWithoutPropertiesInput, {
    nullable: true,
  })
  normalCustomFields?: NormalCustomFieldUpdateManyWithoutPropertiesInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;

  @ApiProperty({
    required: false,
    type: () => PropertyTranslationUpdateManyWithoutPropertiesInput,
  })
  @ValidateNested()
  @Type(() => PropertyTranslationUpdateManyWithoutPropertiesInput)
  @IsOptional()
  @Field(() => PropertyTranslationUpdateManyWithoutPropertiesInput, {
    nullable: true,
  })
  propertyTranslations?: PropertyTranslationUpdateManyWithoutPropertiesInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  size?: number | null;
}

export { PropertyUpdateInput as PropertyUpdateInput };
