/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsInt,
  Min,
  Max,
  IsNumber,
} from "class-validator";
import { AppointmentCreateNestedManyWithoutPropertiesInput } from "./AppointmentCreateNestedManyWithoutPropertiesInput";
import { Type } from "class-transformer";
import { ImageCustomFieldCreateNestedManyWithoutPropertiesInput } from "./ImageCustomFieldCreateNestedManyWithoutPropertiesInput";
import { ListCustomFieldCreateNestedManyWithoutPropertiesInput } from "./ListCustomFieldCreateNestedManyWithoutPropertiesInput";
import { NormalCustomFieldCreateNestedManyWithoutPropertiesInput } from "./NormalCustomFieldCreateNestedManyWithoutPropertiesInput";
import { PropertyTranslationCreateNestedManyWithoutPropertiesInput } from "./PropertyTranslationCreateNestedManyWithoutPropertiesInput";

@InputType()
class PropertyCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: () => AppointmentCreateNestedManyWithoutPropertiesInput,
  })
  @ValidateNested()
  @Type(() => AppointmentCreateNestedManyWithoutPropertiesInput)
  @IsOptional()
  @Field(() => AppointmentCreateNestedManyWithoutPropertiesInput, {
    nullable: true,
  })
  appointments?: AppointmentCreateNestedManyWithoutPropertiesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => ImageCustomFieldCreateNestedManyWithoutPropertiesInput,
  })
  @ValidateNested()
  @Type(() => ImageCustomFieldCreateNestedManyWithoutPropertiesInput)
  @IsOptional()
  @Field(() => ImageCustomFieldCreateNestedManyWithoutPropertiesInput, {
    nullable: true,
  })
  imageCustomFields?: ImageCustomFieldCreateNestedManyWithoutPropertiesInput;

  @ApiProperty({
    required: false,
    type: () => ListCustomFieldCreateNestedManyWithoutPropertiesInput,
  })
  @ValidateNested()
  @Type(() => ListCustomFieldCreateNestedManyWithoutPropertiesInput)
  @IsOptional()
  @Field(() => ListCustomFieldCreateNestedManyWithoutPropertiesInput, {
    nullable: true,
  })
  listCustomFields?: ListCustomFieldCreateNestedManyWithoutPropertiesInput;

  @ApiProperty({
    required: false,
    type: () => NormalCustomFieldCreateNestedManyWithoutPropertiesInput,
  })
  @ValidateNested()
  @Type(() => NormalCustomFieldCreateNestedManyWithoutPropertiesInput)
  @IsOptional()
  @Field(() => NormalCustomFieldCreateNestedManyWithoutPropertiesInput, {
    nullable: true,
  })
  normalCustomFields?: NormalCustomFieldCreateNestedManyWithoutPropertiesInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;

  @ApiProperty({
    required: false,
    type: () => PropertyTranslationCreateNestedManyWithoutPropertiesInput,
  })
  @ValidateNested()
  @Type(() => PropertyTranslationCreateNestedManyWithoutPropertiesInput)
  @IsOptional()
  @Field(() => PropertyTranslationCreateNestedManyWithoutPropertiesInput, {
    nullable: true,
  })
  propertyTranslations?: PropertyTranslationCreateNestedManyWithoutPropertiesInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  size?: number | null;
}

export { PropertyCreateInput as PropertyCreateInput };
