/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { AppointmentListRelationFilter } from "../../appointment/base/AppointmentListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { ImageCustomFieldListRelationFilter } from "../../imageCustomField/base/ImageCustomFieldListRelationFilter";
import { ListCustomFieldListRelationFilter } from "../../listCustomField/base/ListCustomFieldListRelationFilter";
import { NormalCustomFieldListRelationFilter } from "../../normalCustomField/base/NormalCustomFieldListRelationFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { PropertyTranslationListRelationFilter } from "../../propertyTranslation/base/PropertyTranslationListRelationFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";

@InputType()
class PropertyWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  address?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => AppointmentListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AppointmentListRelationFilter)
  @IsOptional()
  @Field(() => AppointmentListRelationFilter, {
    nullable: true,
  })
  appointments?: AppointmentListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => ImageCustomFieldListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ImageCustomFieldListRelationFilter)
  @IsOptional()
  @Field(() => ImageCustomFieldListRelationFilter, {
    nullable: true,
  })
  imageCustomFields?: ImageCustomFieldListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ListCustomFieldListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ListCustomFieldListRelationFilter)
  @IsOptional()
  @Field(() => ListCustomFieldListRelationFilter, {
    nullable: true,
  })
  listCustomFields?: ListCustomFieldListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => NormalCustomFieldListRelationFilter,
  })
  @ValidateNested()
  @Type(() => NormalCustomFieldListRelationFilter)
  @IsOptional()
  @Field(() => NormalCustomFieldListRelationFilter, {
    nullable: true,
  })
  normalCustomFields?: NormalCustomFieldListRelationFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  price?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: () => PropertyTranslationListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PropertyTranslationListRelationFilter)
  @IsOptional()
  @Field(() => PropertyTranslationListRelationFilter, {
    nullable: true,
  })
  propertyTranslations?: PropertyTranslationListRelationFilter;

  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  size?: FloatNullableFilter;
}

export { PropertyWhereInput as PropertyWhereInput };
