/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PropertyService } from "../property.service";
import { PropertyCreateInput } from "./PropertyCreateInput";
import { Property } from "./Property";
import { PropertyFindManyArgs } from "./PropertyFindManyArgs";
import { PropertyWhereUniqueInput } from "./PropertyWhereUniqueInput";
import { PropertyUpdateInput } from "./PropertyUpdateInput";
import { AppointmentFindManyArgs } from "../../appointment/base/AppointmentFindManyArgs";
import { Appointment } from "../../appointment/base/Appointment";
import { AppointmentWhereUniqueInput } from "../../appointment/base/AppointmentWhereUniqueInput";
import { ImageCustomFieldFindManyArgs } from "../../imageCustomField/base/ImageCustomFieldFindManyArgs";
import { ImageCustomField } from "../../imageCustomField/base/ImageCustomField";
import { ImageCustomFieldWhereUniqueInput } from "../../imageCustomField/base/ImageCustomFieldWhereUniqueInput";
import { ListCustomFieldFindManyArgs } from "../../listCustomField/base/ListCustomFieldFindManyArgs";
import { ListCustomField } from "../../listCustomField/base/ListCustomField";
import { ListCustomFieldWhereUniqueInput } from "../../listCustomField/base/ListCustomFieldWhereUniqueInput";
import { NormalCustomFieldFindManyArgs } from "../../normalCustomField/base/NormalCustomFieldFindManyArgs";
import { NormalCustomField } from "../../normalCustomField/base/NormalCustomField";
import { NormalCustomFieldWhereUniqueInput } from "../../normalCustomField/base/NormalCustomFieldWhereUniqueInput";
import { PropertyTranslationFindManyArgs } from "../../propertyTranslation/base/PropertyTranslationFindManyArgs";
import { PropertyTranslation } from "../../propertyTranslation/base/PropertyTranslation";
import { PropertyTranslationWhereUniqueInput } from "../../propertyTranslation/base/PropertyTranslationWhereUniqueInput";

export class PropertyControllerBase {
  constructor(protected readonly service: PropertyService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Property })
  async createProperty(
    @common.Body() data: PropertyCreateInput
  ): Promise<Property> {
    return await this.service.createProperty({
      data: data,
      select: {
        address: true,
        createdAt: true,
        description: true,
        id: true,
        price: true,
        size: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Property] })
  @ApiNestedQuery(PropertyFindManyArgs)
  async properties(@common.Req() request: Request): Promise<Property[]> {
    const args = plainToClass(PropertyFindManyArgs, request.query);
    return this.service.properties({
      ...args,
      select: {
        address: true,
        createdAt: true,
        description: true,
        id: true,
        price: true,
        size: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Property })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async property(
    @common.Param() params: PropertyWhereUniqueInput
  ): Promise<Property | null> {
    const result = await this.service.property({
      where: params,
      select: {
        address: true,
        createdAt: true,
        description: true,
        id: true,
        price: true,
        size: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Property })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateProperty(
    @common.Param() params: PropertyWhereUniqueInput,
    @common.Body() data: PropertyUpdateInput
  ): Promise<Property | null> {
    try {
      return await this.service.updateProperty({
        where: params,
        data: data,
        select: {
          address: true,
          createdAt: true,
          description: true,
          id: true,
          price: true,
          size: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Property })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteProperty(
    @common.Param() params: PropertyWhereUniqueInput
  ): Promise<Property | null> {
    try {
      return await this.service.deleteProperty({
        where: params,
        select: {
          address: true,
          createdAt: true,
          description: true,
          id: true,
          price: true,
          size: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/appointments")
  @ApiNestedQuery(AppointmentFindManyArgs)
  async findAppointments(
    @common.Req() request: Request,
    @common.Param() params: PropertyWhereUniqueInput
  ): Promise<Appointment[]> {
    const query = plainToClass(AppointmentFindManyArgs, request.query);
    const results = await this.service.findAppointments(params.id, {
      ...query,
      select: {
        agent: {
          select: {
            id: true,
          },
        },

        client: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        date: true,
        id: true,
        notes: true,

        property: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/appointments")
  async connectAppointments(
    @common.Param() params: PropertyWhereUniqueInput,
    @common.Body() body: AppointmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      appointments: {
        connect: body,
      },
    };
    await this.service.updateProperty({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/appointments")
  async updateAppointments(
    @common.Param() params: PropertyWhereUniqueInput,
    @common.Body() body: AppointmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      appointments: {
        set: body,
      },
    };
    await this.service.updateProperty({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/appointments")
  async disconnectAppointments(
    @common.Param() params: PropertyWhereUniqueInput,
    @common.Body() body: AppointmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      appointments: {
        disconnect: body,
      },
    };
    await this.service.updateProperty({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/imageCustomFields")
  @ApiNestedQuery(ImageCustomFieldFindManyArgs)
  async findImageCustomFields(
    @common.Req() request: Request,
    @common.Param() params: PropertyWhereUniqueInput
  ): Promise<ImageCustomField[]> {
    const query = plainToClass(ImageCustomFieldFindManyArgs, request.query);
    const results = await this.service.findImageCustomFields(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        image: true,

        property: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/imageCustomFields")
  async connectImageCustomFields(
    @common.Param() params: PropertyWhereUniqueInput,
    @common.Body() body: ImageCustomFieldWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      imageCustomFields: {
        connect: body,
      },
    };
    await this.service.updateProperty({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/imageCustomFields")
  async updateImageCustomFields(
    @common.Param() params: PropertyWhereUniqueInput,
    @common.Body() body: ImageCustomFieldWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      imageCustomFields: {
        set: body,
      },
    };
    await this.service.updateProperty({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/imageCustomFields")
  async disconnectImageCustomFields(
    @common.Param() params: PropertyWhereUniqueInput,
    @common.Body() body: ImageCustomFieldWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      imageCustomFields: {
        disconnect: body,
      },
    };
    await this.service.updateProperty({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/listCustomFields")
  @ApiNestedQuery(ListCustomFieldFindManyArgs)
  async findListCustomFields(
    @common.Req() request: Request,
    @common.Param() params: PropertyWhereUniqueInput
  ): Promise<ListCustomField[]> {
    const query = plainToClass(ListCustomFieldFindManyArgs, request.query);
    const results = await this.service.findListCustomFields(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        label: true,

        property: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/listCustomFields")
  async connectListCustomFields(
    @common.Param() params: PropertyWhereUniqueInput,
    @common.Body() body: ListCustomFieldWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      listCustomFields: {
        connect: body,
      },
    };
    await this.service.updateProperty({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/listCustomFields")
  async updateListCustomFields(
    @common.Param() params: PropertyWhereUniqueInput,
    @common.Body() body: ListCustomFieldWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      listCustomFields: {
        set: body,
      },
    };
    await this.service.updateProperty({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/listCustomFields")
  async disconnectListCustomFields(
    @common.Param() params: PropertyWhereUniqueInput,
    @common.Body() body: ListCustomFieldWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      listCustomFields: {
        disconnect: body,
      },
    };
    await this.service.updateProperty({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/normalCustomFields")
  @ApiNestedQuery(NormalCustomFieldFindManyArgs)
  async findNormalCustomFields(
    @common.Req() request: Request,
    @common.Param() params: PropertyWhereUniqueInput
  ): Promise<NormalCustomField[]> {
    const query = plainToClass(NormalCustomFieldFindManyArgs, request.query);
    const results = await this.service.findNormalCustomFields(params.id, {
      ...query,
      select: {
        content: true,
        createdAt: true,
        id: true,
        label: true,

        property: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/normalCustomFields")
  async connectNormalCustomFields(
    @common.Param() params: PropertyWhereUniqueInput,
    @common.Body() body: NormalCustomFieldWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      normalCustomFields: {
        connect: body,
      },
    };
    await this.service.updateProperty({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/normalCustomFields")
  async updateNormalCustomFields(
    @common.Param() params: PropertyWhereUniqueInput,
    @common.Body() body: NormalCustomFieldWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      normalCustomFields: {
        set: body,
      },
    };
    await this.service.updateProperty({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/normalCustomFields")
  async disconnectNormalCustomFields(
    @common.Param() params: PropertyWhereUniqueInput,
    @common.Body() body: NormalCustomFieldWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      normalCustomFields: {
        disconnect: body,
      },
    };
    await this.service.updateProperty({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/propertyTranslations")
  @ApiNestedQuery(PropertyTranslationFindManyArgs)
  async findPropertyTranslations(
    @common.Req() request: Request,
    @common.Param() params: PropertyWhereUniqueInput
  ): Promise<PropertyTranslation[]> {
    const query = plainToClass(PropertyTranslationFindManyArgs, request.query);
    const results = await this.service.findPropertyTranslations(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        id: true,

        locale: {
          select: {
            id: true,
          },
        },

        property: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/propertyTranslations")
  async connectPropertyTranslations(
    @common.Param() params: PropertyWhereUniqueInput,
    @common.Body() body: PropertyTranslationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      propertyTranslations: {
        connect: body,
      },
    };
    await this.service.updateProperty({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/propertyTranslations")
  async updatePropertyTranslations(
    @common.Param() params: PropertyWhereUniqueInput,
    @common.Body() body: PropertyTranslationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      propertyTranslations: {
        set: body,
      },
    };
    await this.service.updateProperty({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/propertyTranslations")
  async disconnectPropertyTranslations(
    @common.Param() params: PropertyWhereUniqueInput,
    @common.Body() body: PropertyTranslationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      propertyTranslations: {
        disconnect: body,
      },
    };
    await this.service.updateProperty({
      where: params,
      data,
      select: { id: true },
    });
  }
}
